config/routes.rb
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  get "/r/mobile", to: "deep_links#mobile"
  get "/.well-known/apple-app-site-association", to: "deep_links#aasa"

  scope "(/::locale)", defaults: { locale: nil } do
    get "/", to: "stories#index"
    require "sidekiq/web"
    require "sidekiq_unique_jobs/web"
    require "sidekiq/cron/web"

    authenticated :user, ->(user) { user.tech_admin? } do
      Sidekiq::Web.class_eval do
        use Rack::Protection, permitted_origins: [URL.url] # resolve Rack Protection HttpOrigin
      end
      mount Sidekiq::Web => "/sidekiq"
      mount FieldTest::Engine, at: "abtests"
    end

    draw :admin

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        resource :pinned_article, only: %w[show update destroy]

        get ":timeframe", to: "feeds#show", as: :timeframe
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
            get "/latest", to: "articles#index", defaults: { sort: "desc" }
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :readinglist, only: [:index]
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end
        resource :instance, only: %i[show]
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    namespace :users do
      resource :settings, only: %i[update]
      resource :notification_settings, only: %i[update]
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :events, only: %i[index show]
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :html_variant_trials, only: [:create]
    resources :html_variant_successes, only: [:create]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :listings, only: %i[index new create edit update destroy dashboard]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :video_chats, only: %i[show]
    resources :sidebars, only: %i[show]
    resources :profile_preview_cards, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end
    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    resource :onboarding, only: :show
    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    resources :discussion_locks, only: %i[create destroy]

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/chat_channels", to: "search#chat_channels"
    get "/search/listings", to: "search#listings"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/chat_channel_memberships/find_by_chat_channel_id", to: "chat_channel_memberships#find_by_chat_channel_id"
    get "/listings/dashboard", to: "listings#dashboard"
    get "/listings/:category", to: "listings#index", as: :listing_category
    get "/listings/:category/:slug", to: "listings#index", as: :listing_slug
    get "/listings/:category/:slug/:view", to: "listings#index",
                                           constraints: { view: /moderate/ }
    get "/listings/:category/:slug/delete_confirm", to: "listings#delete_confirm"
    delete "/listings/:category/:slug", to: "listings#destroy"
    get "/notifications/:filter", to: "notifications#index"
    get "/notifications/:filter/:org_id", to: "notifications#index"
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    patch "/onboarding_update", to: "users#onboarding_update"
    patch "/onboarding_checkbox_update", to: "users#onboarding_checkbox_update"
    patch "/onboarding_notifications_checkbox_update",
          to: "users/notification_settings#onboarding_notifications_checkbox_update"
    get "email_subscriptions/unsubscribe"
    post "/chat_channels/:id/moderate", to: "chat_channels#moderate"
    post "/chat_channels/:id/open", to: "chat_channels#open"
    get "/connect", to: "chat_channels#index"
    get "/connect/:slug", to: "chat_channels#index"
    get "/chat_channels/:id/channel_info", to: "chat_channels#channel_info", as: :chat_channel_info
    post "/chat_channels/create_chat", to: "chat_channels#create_chat"
    post "/chat_channels/block_chat", to: "chat_channels#block_chat"
    post "/chat_channel_memberships/remove_membership", to: "chat_channel_memberships#remove_membership"
    post "/chat_channel_memberships/add_membership", to: "chat_channel_memberships#add_membership"
    post "/join_chat_channel", to: "chat_channel_memberships#join_channel"

app/controllers/notifications/counts_controller.rb
module Notifications
  class CountsController < ApplicationController
    def index
      count = current_user ? current_user.notifications.unread.count : 0
      render plain: count.to_s
    end
  end
end

app/controllers/notifications/reads_controller.rb
module Notifications
  class ReadsController < ApplicationController
    def create
      render plain: "" && return unless current_user

      current_user.notifications.unread.update_all(read: true)
      current_user.touch(:last_notification_activity)

      if params[:org_id] && current_user.org_member?(params[:org_id])
        org = Organization.find_by(id: params[:org_id])
        org.notifications.unread.update_all(read: true)
      end

      render plain: "read"
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/PerceivedComplexity
  # No authorization required because we provide authentication on notifications page
  def index
    return unless user_signed_in?

    @notifications_index = true
    @user = user_to_view

    @initial_page_size = 8

    # NOTE: this controller is using offset based pagination by assuming that
    # the id of the last notification also corresponds to the newest `notified_at`
    # this might not be forever true but it's good enough for now
    if params[:offset]
      num = 30
      notified_at_offset = Notification.find(params[:offset])&.notified_at
    else
      num = @initial_page_size
    end

    @notifications = if (params[:org_id].present? || params[:filter] == "org") && allowed_user?
                       organization_notifications
                     elsif params[:org_id].blank? && params[:filter].present?
                       filtered_notifications
                     else
                       @user.notifications
                     end

    @notifications = @notifications.order(notified_at: :desc)

    # if offset based pagination is invoked by the frontend code, we filter out all earlier ones
    @notifications = @notifications.where("notified_at < ?", notified_at_offset) if notified_at_offset

    @notifications = @notifications.limit(num)

    @notifications = NotificationDecorator.decorate_collection(@notifications)

    @last_user_reaction = @user.reactions.last&.id
    @last_user_comment = @user.comments.last&.id

    @organizations = @user.member_organizations if @user.organizations
    @selected_organization = Organization.find(params[:org_id]) if params[:org_id].present?

    # The first call, the one coming from the browser URL bar will render the "index" view, which renders
    # the first few notifications. After that the JS frontend code (see `initNotification.js`)
    # will call this action again by sending the offset id for the last known notifications, the result
    # will be the partial rendering of only the list of notifications that will be attached to the DOM by JS
    render partial: "notifications_list" if notified_at_offset
  end
  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/PerceivedComplexity

  private

  def user_to_view
    if params[:username] && current_user.admin?
      User.find_by(username: params[:username])
    else
      current_user
    end
  end

  def filtered_notifications
    if params[:filter].to_s.casecmp("posts").zero?
      @user.notifications.for_published_articles
    elsif params[:filter].to_s.casecmp("comments").zero?
      @user.notifications.for_comments.or(@user.notifications.for_mentions)
    else
      @user.notifications
    end
  end

  def organization_notifications
    org_id = params[:org_id]

    if params[:filter].to_s.casecmp("comments").zero?
      Notification.for_organization_comments(org_id).or(Notification.for_organization_mentions(org_id))
    else
      Notification.for_organization(org_id)
    end
  end

  def allowed_user?
    @user.org_member?(params[:org_id]) || @user.admin?
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  REACTION_IMAGES = {
    "like" => "heart-filled.svg",
    "unicorn" => "unicorn-filled.svg",
    "hands" => "emoji/emoji-one-hands.png",
    "thinking" => "emoji/emoji-one-thinking.png",
    "readinglist" => "save-filled.svg",
    "thumbsdown" => "emoji/emoji-one-thumbs-down.png",
    "vomit" => "emoji/emoji-one-nausea-face.png"
  }.freeze

  def reaction_image(category)
    REACTION_IMAGES[category]
  end
end

app/views/notifications/_aggregated_reactions.html.erb
<% _t = t.v.notifications.reacted %>
<%# TODO: change to map of IDs %>
<% actors = siblings.map { |n| n["user"] }.uniq %>
<% reactable_data = notification.json_data["reaction"]["reactable"] %>

<div class="relative shrink-0 self-start">
  <% if actors.size == 1 %>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l m:crayons-avatar--xl" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.first["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.first["username"] %>'s profile" width="48" height="48">
    </a>
  <% else %>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l mr-4" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.first["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.first["username"] %>'s profile" width="48" height="48">
    </a>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l absolute -right-1 -bottom-3 border-solid border-2 border-base-inverted" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.last["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.last["username"] %>'s profile" width="48" height="48">
    </a>
  <% end %>
</div>

<div class="notification__content pt-2">
  <% reaction_categories = siblings.map { |n| n["category"] } %>
  <%= _t.verb(
    count: actors.size,
    start: tag("span", { class: %w[inline-block py-1] }, true),
    actors: if actors.size == 1
      link_to actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"
    elsif actors.size == 2
      _t.and(
        first: link_to(actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"),
        last: link_to(actors.last["name"], actors.last["path"], class: "crayons-link fw-bold"),
      )
    elsif actors.size > 1
      _t.other(
        first: link_to(actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"),
        count: actors.size - 1,
      )
    end,
    # your article/comment or the actual title of the article/comment
    title: link_to(reactable_data["title"].blank? ? _t.your[reactable_data['class']['name'].downcase] : h(reactable_data["title"]), reactable_data["path"], class: "crayons-link fw-bold")
    end: "</span>".html_safe,
    reactions: reaction_categories.map do |cat|
      image_path = reaction_image(cat)
      if image_path.present?
        inline_svg_tag(image_path, aria: true, class: "crayons-icon reaction-image mx-1 my-1 reaction-icon--#{cat}", title: t.v.reactions.category[cat.to_s])
      end
    end.compact.safe_join("\n"),
  ) %>
</div>

app/views/notifications/_article.html.erb
<% _t = t.v.notifications.new_post %>
<div class="crayons-card notification">
  <% if notification.action == "Reaction" %>
    <%= render "reaction", notification: notification %>
  <% elsif notification.action.include? "Milestone" %>
    <%= render "milestone", notification: notification %>
  <% else %>
    <% json_data = notification.json_data %>
    <%= render "notifications/shared/profile_pic", json_data: json_data %>

    <div class="notification__content">
      <header class="mb-4">
        <h2 class="fs-base fw-normal">
          <%= _t.verb(
                user: link_to(json_data["user"]["name"], json_data["user"]["path"], class: "crayons-link fw-bold"),
                if_org: if json_data["organization"]
                          link_to json_data["organization"]["name"], json_data["organization"]["path"], class: "crayons-link fw-bold"
                        else
                          ""
                        end,
              ) %>
        </h2>
        <p class="lh-tight"><small class="fs-s color-base-60"><%= time_ago_in_words json_data["article"]["published_at"], scope: :'datetime.distance_in_words_ago' %></small></p>
      </header>

      <%= render "notifications/shared/article_preview", json_data: json_data, notification: notification, context: "default" %>
    </div>
  <% end %>
</div>

app/views/notifications/_badgeachievement.html.erb
<% _t = t.v.notifications.badge %>
<% json_data = notification.json_data %>
<div class="crayons-card notification notification--promoted grid gap-4">
    <header class="mb-2 m:mb-4">
      <h3 class="fw-normal fs-l s:fs-xl m:fs-2xl">
      <%= _t.heading badge: tag.strong(sanitize(json_data["badge_achievement"]["badge"]["title"]), class: "fw-bold") %>
      </h3>
      <p class="fs-l"><%= json_data["badge_achievement"]["badge"]["description"] %></p>
    </header>

    <div class="crayons-card crayons-card--secondary p-4 w-100 grid gap-2">
      <img class="w-100 max-w-50 l:max-w-25 h-auto inline-block mx-auto" src="<%= optimized_image_url(json_data["badge_achievement"]["badge"]["badge_image_url"], width: 250) %>" alt="<%= json_data["badge_achievement"]["badge"]["title"] %>">
      <p class="color-base-70"><em><%= json_data["badge_achievement"]["rewarding_context_message"].to_s.html_safe %></em></p>
    </div>

  <p class="self-stretch"><a href="<%= json_data["user"]["path"] %>" class="crayons-btn w-100 m:w-50"><%= _t.profile %></a></p>
  <% credits_awarded = json_data["badge_achievement"]["badge"]["credits_awarded"] %>
  <% unless credits_awarded.present? && credits_awarded.zero? %>
    <p class="max-w-75 mx-auto"><%= _t.awarded credits: link_to(_t.credits(json_data["badge_achievement"]["badge"]["credits_awarded"]), "/credits", class: "crayons-link crayons-link--brand fw-bold"), listings: link_to(_t.listings, "/listings") %></p>
    <p class="fs-s"><a href="<%= about_listings_url %>" class="crayons-link crayons-link--secondary"><%= _t.more %><a></p>
  <% end %>
</div>

app/views/notifications/_broadcast.html.erb
<% _t = t.v.notifications.broadcast %>
<div class="crayons-card notification notification--promoted">
  <% json_data = notification.json_data %>
  <% user = User.find_by(id: json_data["user"]["id"]) %>
  <% cache "broadcast-html-#{notification.json_data['broadcast']['title']}" do %>
    <a href="<%= json_data["user"]["path"] %>" class="crayons-avatar crayons-avatar--2xl m:crayons-avatar--3xl shrink-0 mb-4 m:mb-6">
      <img src="<%= Images::Profile.call(user.profile_image_url) %>" class="crayons-avatar__image" alt="link to <%= json_data["user"]["username"] %>'s profile" width="128" height="128">
    </a>
    <div class="fs-base m:fs-l broadcast-content" id="<%= sanitized_broadcast_id(json_data["broadcast"]["title"]) %>">
      <%= json_data["broadcast"]["processed_html"].html_safe %>

      <% if notification.json_data['broadcast']['type_of'] == "Welcome" %>
        <p class="fs-base pt-6 color-base-70"><%= _t.visit settings: link_to(_t.settings, user_settings_path(tab: :notifications)) %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/notifications/_comment.html.erb
<% _t = t.v.notifications.comment %>
<div class="crayons-card notification">
  <% if notification.action == "Reaction" %>
    <%= render "reaction", notification: notification %>
  <% else %>
    <% json_data = notification.json_data %>
    <% cache "activity-profile-pic-#{json_data['user']['id']}-#{json_data['user']['profile_image_90']}" do %>
      <%= render "notifications/shared/profile_pic", json_data: json_data %>
    <% end %>

    <div class="notification__content">
      <% if notification.action.blank? %>
        <% params = { user: link_to(json_data["user"]["name"], json_data["user"]["path"], class: "crayons-link fw-bold"), title: link_to(h(json_data["comment"]["commentable"]["title"]), json_data["comment"]["commentable"]["path"], class: "crayons-link fw-bold") } %>
        <% if json_data["comment"]["created_at"] %>
          <header class="mb-4">
            <h2 class="fs-base fw-normal">
              <% if json_data["comment"]["depth"] && json_data["comment"]["depth"] > 0 %>
                <%= _t.replied params %>
              <% else %>
                <%= _t.commented params %>
              <% end %>
            </h2>
            <p class="lh-tight"><a href="<%= json_data["comment"]["path"] %>" class="crayons-link fs-s crayons-link--secondary"><%= time_ago_in_words json_data["comment"]["created_at"], scope: :'datetime.distance_in_words_ago' %></a></p>
          </header>
        <% end %>

        <%= render "notifications/shared/comment_box", json_data: json_data, notification: notification, context: "default" %>

      <% elsif notification.action == "Moderation" %>
        <header class="mb-4">
          <h2 class="fs-base fw-normal">
            <%# TODO (yheuhtozr): check if the user param is designed correctly %>
            <%= _t.left user: link_to(json_data["comment"]["path"].split("/")[1], "/#{json_data['comment']['path'].split('/')[1]}", class: "crayons-link fw-bold"), title: params[:title] %>
          </h2>
          <p><%= _t.welcome %></p>
        </header>

        <%= render "notifications/shared/comment_box", json_data: json_data, notification: notification, context: "moderation" %>

        <p class="fs-s color-base-60 pt-4"><%= _t.report %></p>

      <% elsif notification.action == "First" %>
        <header class="mb-4">
          <h2 class="fs-base fw-normal">
            <%= _t.first params %>
          </h2>
          <p class="lh-tight"><small class="fs-s color-base-60"><%= time_ago_in_words notification.created_at, scope: :'datetime.distance_in_words_ago' %></small></p>

          <p><%= _t.first_reply %></p>
        </header>

        <%= render "notifications/shared/comment_box", activity: activity, context: "moderation" %>

      <% end %>
    </div>
  <% end %>
</div>

app/views/notifications/_mention.html.erb
<% _t = t.v.notifications.mention %>
<div class="crayons-card notification">
  <% json_data = notification.json_data %>
  <% cache "activity-profile-pic-#{json_data['user']['id']}-#{json_data['user']['profile_image_90']}" do %>
    <%= render "notifications/shared/profile_pic", json_data: json_data %>
  <% end %>

  <div class="notification__content">
    <% if notification.json_data["article"] %>
      <header class="mb-4">
        <h2 class="fs-base fw-normal">
          <%= _t.article(
                user: link_to(json_data["user"]["name"], json_data["user"]["path"], class: "crayons-link fw-bold"),
                if_org: if json_data["organization"]
                          link_to json_data["organization"]["name"], json_data["organization"]["path"], class: "crayons-link fw-bold"
                        else
                          ""
                        end,
              ) %>
        </h2>
        <p class="lh-tight"><small class="fs-s color-base-60"><%= time_ago_in_words json_data["article"]["published_at"], scope: :'datetime.distance_in_words_ago' %></small></p>
      </header>

      <%= render "notifications/shared/article_preview", json_data: json_data, notification: notification, context: "default" %>
    <% elsif notification.json_data["comment"] %>
      <h2 class="fs-base fw-normal mb-4">
        <%= _t.comments user: link_to(json_data["user"]["name"], json_data["user"]["path"], class: "crayons-link fw-bold") %>
      </h2>
      <%= render "notifications/shared/comment_box", json_data: json_data, notification: notification, context: "default" %>
    <% end %>
  </div>
</div>

app/views/notifications/_reaction.html.erb
<%# missing cache key %>
<% siblings = notification.json_data["reaction"]["aggregated_siblings"].select { |n| n["created_at"] > 24.hours.ago } %>
<% if siblings.length == 0 %>
  <%= render "single_reaction", notification: notification %>
<% else %>
  <%= render "aggregated_reactions", notification: notification, siblings: siblings %>
<% end %>

app/views/notifications/index.html.erb
<% _t = t.v.notifications %>
<% title _t.heading %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/notifications") %>" />
  <meta name="description" content="<%= _t.meta.description community: community_name %>">
  <%= meta_keywords_default %>

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/notifications") %>" />
  <meta property="og:title" content="<%= _t.meta.og.title community: community_name %>" />
  <meta property="og:description" content="<%= _t.meta.description community: community_name %>" />
  <meta property="og:site_name" content="<%= community_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= Settings::General.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="<%= _t.meta.og.title community: community_name %>">
  <meta name="twitter:description" content="<%= _t.meta.description community: community_name %>">

   <%= javascript_packs_with_chunks_tag "notificationPage", defer: true %>
<% end %>

<script>
  /**
   * A script that tracks clicks for welcome notifications.
   * The notification must have `trackNotification` as its onclick event
   * in order for this to be triggered.
   *
   * @param {Event} The click event on the notification.
   */
  function trackNotification(event) {
    const target = event.target;
    const { parentElement: { id: title }, text } = target;

    // TODO: [@forem/delightful]: This event doesn't appear to be firing on Honeybadger.
    // We probably want to remove it eventually if we continually don't see it being triggered.
    if (!title) {
      Honeybadger.notify(`Could not find parentElement.id when clicking on event target text: ${text}`);
    }

    ahoy.track("Clicked Welcome Notification", { title, text, target: target.toString() });
  }
</script>

<% if user_signed_in? %>
  <main id="main-content">
    <header class="crayons-layout crayons-layout--limited-l crayons-layout--1-col p-4 flex items-center justify-between">
      <h1 class="crayons-title"><%= _t.heading %></h1>
      <a href="<%= user_settings_path(tab: :notifications) %>" class="crayons-btn crayons-btn--ghost"><%= _t.settings %></a>
    </header>

    <div class="crayons-layout crayons-layout--limited-l crayons-layout--2-cols pt-0" id="notifications-container">
      <div class="crayons-layout__sidebar-left">
        <%= render "notifications/nav_menu" %>
      </div>
      <main class="crayons-layout__content" data-follow-button-container="true">
        <div id="articles-list">
          <%= render "notifications_list", params: params %>
        </div>

        <%# new or less active users that don't have a page worth of notifications
            won't be shown the "load more" button %>
        <% if @notifications.size >= @initial_page_size %>
          <button id="load-more-button" type="button" class="crayons-btn crayons-btn--secondary crayons-btn--l my-6 w-100">
            <%= _t.load %>
          </button>
        <% end %>
      </main>
    </div>
    <%= render "articles/fitvids" %>
  </main>
  <%= javascript_packs_with_chunks_tag "followButtons", defer: true %>
<% else %>
  <%= render "devise/registrations/registration_form" %>
<% end %>